"use client";

import { createElement } from "react";
import type { IconKey } from "@mdxeditor/editor";
import type { LucideIcon } from "lucide-react";
import {
  AlignCenter,
  AlignLeft,
  AlignRight,
  Bold,
  Check,
  ChevronDown,
  Code2,
  Columns2,
  Copy,
  Diff,
  Edit,
  ExternalLink,
  FileCode2,
  Heading,
  Highlighter,
  ImagePlus,
  Italic,
  Link2,
  Link2Off,
  List,
  ListChecks,
  ListOrdered,
  Minus,
  MoreHorizontal,
  MoreVertical,
  Pencil,
  Quote,
  Redo2,
  Rows2,
  Settings,
  Strikethrough,
  Subscript,
  Superscript,
  Table2,
  Trash2,
  Underline,
  Undo2,
  Unlink,
  X,
} from "lucide-react";

const ICON_MAP: Record<IconKey, LucideIcon> = {
  undo: Undo2,
  redo: Redo2,
  format_bold: Bold,
  format_italic: Italic,
  format_underlined: Underline,
  code: Code2,
  strikeThrough: Strikethrough,
  superscript: Superscript,
  subscript: Subscript,
  format_list_bulleted: List,
  format_list_numbered: ListOrdered,
  format_list_checked: ListChecks,
  format_highlight: Highlighter,
  link: Link2,
  add_photo: ImagePlus,
  table: Table2,
  horizontal_rule: Minus,
  frontmatter: FileCode2,
  frame_source: Code2,
  arrow_drop_down: ChevronDown,
  admonition: Quote,
  rich_text: Pencil,
  difference: Diff,
  markdown: Heading,
  open_in_new: ExternalLink,
  link_off: Link2Off,
  edit: Edit,
  content_copy: Copy,
  more_horiz: MoreHorizontal,
  more_vert: MoreVertical,
  close: X,
  settings: Settings,
  delete_big: Trash2,
  delete_small: Trash2,
  format_align_center: AlignCenter,
  format_align_left: AlignLeft,
  format_align_right: AlignRight,
  add_row: Rows2,
  add_column: Columns2,
  insert_col_left: Columns2,
  insert_row_above: Rows2,
  insert_row_below: Rows2,
  insert_col_right: Columns2,
  check: Check,
};

/** MDXEditor iconComponentFor → Lucide */
export function mdxLucideIcon(name: IconKey) {
  const Icon = ICON_MAP[name] ?? Unlink;
  return createElement(Icon, {
    className: "mdx-lucide-icon",
    strokeWidth: 1.75,
    "aria-hidden": true,
  });
}
